// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 15.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerate.T4Template.Golang.Model
{
    using Kalman;
    using Kalman.Extensions;
    using Kalman.Data;
    using Kalman.Data.SchemaObject;
    using Kalman.Data.DbSchemaProvider;
    using Kalman.Data.DbProvider;
    using Kalman.Utilities;
    using CodeGenerate.T4TemplateEngineHost;
    using System;
    using System.IO;
    using System.Xml;
    using System.Linq;
    using System.Text;
    using System.Data;
    using System.Data.Common;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.Specialized;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class Model : ModelBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 21 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
 
	TableHost host = (TableHost)(Host);
	SOTable table = host.Table;
	List<SOColumn> colList = host.ColumnList;
    int maxColumnNameLength=colList.Max(tmp=>tmp.Name.Length);
    string className = CSharpHostHelper.GetCamelCaseName(table.Name);
    string nameSpace = CSharpHostHelper.FirstLower(className);

            
            #line default
            #line hidden
            this.Write("package ");
            
            #line 29 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nameSpace));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n// 模块名\r\nconst ModuleName = \"");
            
            #line 32 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("\"\r\n\r\n// 调度日志\r\ntype ");
            
            #line 35 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" struct {\r\n");
            
            #line 36 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
 foreach (SOColumn c in colList){ 
            
            #line default
            #line hidden
            this.Write("\r\n        // ");
            
            #line 38 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c.Comment == "" ? c.Name : c.Comment.Replace("\r\n"," ")));
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 39 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 39 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeUtil.DbType2GolangTypeString(c.DataType)));
            
            #line default
            #line hidden
            this.Write(" `gorm:\"Column:");
            
            #line 39 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c.Name));
            
            #line default
            #line hidden
            
            #line 39 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c.PrimaryKey?";PRIMARY_KEY":""));
            
            #line default
            #line hidden
            this.Write("\"`\r\n");
            
            #line 40 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
 } 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n// 表名\r\nfunc (this *");
            
            #line 44 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(") TableName() string {\r\n\treturn \"");
            
            #line 45 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name));
            
            #line default
            #line hidden
            this.Write("\"\r\n}\r\n\r\n// 新建调度模型对象\r\nfunc New");
            
            #line 49 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("() *");
            
            #line 49 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" {\r\n\treturn &");
            
            #line 50 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("{}\r\n}\r\n\r\n// 新建调度模型对象\r\n");
            
            #line 54 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
foreach(SOColumn item in colList) {
            
            #line default
            #line hidden
            this.Write("// ");
            
            #line 55 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name.FirstLower()));
            
            #line default
            #line hidden
            this.Write(":");
            
            #line 55 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 56 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
}
            
            #line default
            #line hidden
            this.Write("func New");
            
            #line 57 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("2(");
            
            #line 57 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", colList.Select(tmp=>String.Format("{0} {1}",tmp.Name.FirstLower(),TypeUtil.DbType2GolangTypeString(tmp.DataType))))));
            
            #line default
            #line hidden
            this.Write(") *");
            
            #line 57 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" {\r\n\treturn &");
            
            #line 58 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("{\r\n");
            
            #line 59 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
foreach(SOColumn item in colList) {
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 60 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 60 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CSharpHostHelper.GetRepeatString(" ", maxColumnNameLength-item.Name.Length)));
            
            #line default
            #line hidden
            
            #line 60 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name.FirstLower()));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 61 "E:\cust\开源项目\csharp\ToolManager\CodeGenerate\T4Template\Golang\Model\Model.tt"
}
            
            #line default
            #line hidden
            this.Write("\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        /// <summary>
        /// The current host for the text templating engine
        /// </summary>
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class ModelBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
